version: "3.5"
services:
    mysql-mysql:
        image: mysql:8
        container_name: mysql-mysql
        hostname: mysql-mysql
        restart: always
        ports:
            - 3306:3306
        networks:
            - mysql-net
        env_file:
            - ./common.env
        environment:
            - MYSQL_ROOT_PASSWORD=chinese
        volumes:
            - ./mysql:/docker-entrypoint-initdb.d
            - ./mysql/mysql.cnf:/etc/mysql/conf.d/my.cnf
            - ~/repository/docker/mysql/logs:/logs
            - ~/repository/docker/mysql/data:/var/lib/mysql 
networks:
    mysql-net:
        driver: bridge