version: "3.5"
services:
    nginx-nginx:
        image: nginx:stable
        container_name: nginx-nginx
        hostname: nginx-nginx
        restart: always
        ports:
            - 80:80
        networks:
            - nginx_net
        env_file:
            - ./common.env
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ~/repository/docker/doc/:/doc/
            - ~/repository/docker/nginx/logs:/etc/nginx/logs
networks:
    nginx-net:
        driver: bridge