add_newline = false
format = """
$username\
$hostname\
$directory\
$package\
$git_branch\
$git_metrics\
$git_status\
$cmake\
$cobol\
$conda\
$crystal\
$dart\
$deno\
$docker_context\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$rlang\
$ruby\
$rust\
$scala\
$swift\
$vagrant\
$vlang\
$zig\
$character\
"""
right_format = """
$time\
$cmd_duration\
$jobs\
$memory_usage\
$battery
"""

[username]
format = "[$user]($style)"
show_always = true

[hostname]
format = "@[$hostname]($style) "
ssh_only = false

[package]
format = "[$symbol$version]($style)"

[git_branch]
format = "[$symbol$branch]($style)"

[git_metrics]
format = '([+$added]($added_style))([-$deleted]($deleted_style))'

[cmake]
format = "[$symbol($version)]($style)"

[cobol]
format = "[$symbol($version)]($style)"

[conda]
format = "[$symbol$environment]($style)"

[crystal]
format = "[$symbol($version)]($style)"

[dart]
format = "[$symbol($version)]($style)"

[deno]
format = "[$symbol($version)]($style)"

[docker_context]
format = "[$symbol$context]($style)"

[dotnet]
format = "[$symbol($version)(🎯$tfm)]($style)"

[elixir]
format = '[$symbol($version\(OTP $otp_version\))]($style)'

[elm]
format = "[$symbol($version)]($style)"

[erlang]
format = "[$symbol($version)]($style)"

[golang]
format = "[$symbol($version)]($style)"

[helm]
format = "[$symbol($version)]($style)"

[java]
format = "[${symbol}(${version})]($style)"

[julia]
format = "[$symbol($version)]($style)"

[kotlin]
format = "[$symbol($version)]($style)"

[lua]
format = "[$symbol($version)]($style)"

[nim]
format = "[$symbol($version)]($style)"

[nodejs]
format = "[$symbol($version)]($style)"

[ocaml]
format = '[$symbol($version)(\($switch_indicator$switch_name\))]($style)'

[perl]
format = "[$symbol($version)]($style)"

[php]
format = "[$symbol($version)]($style)"

[purescript]
format = "[$symbol($version )]($style)"

[python]
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)'

[rlang]
format = "[$symbol($version)]($style)"

[ruby]
format = "[$symbol($version)]($style)"

[rust]
format = "[$symbol($version)]($style)"

[scala]
format = "[$symbol($version)]($style)"

[swift]
format = "[$symbol($version)]($style)"

[vagrant]
format = "[$symbol($version)]($style)"

[vlang]
format = "[$symbol($version)]($style)"

[zig]
format = "[$symbol($version)]($style)"

[time]
format = '🕙[$time]($style) '
time_format = "%Y-%m-%d %H:%M:%S"
disabled = false

[cmd_duration]
format = "[$duration]($style) "
min_time = 2000

[jobs]
format = "[$symbol$number]($style) "

[memory_usage]
format = "[$ram_pct]($style) "
threshold = -1
disabled = false

[battery]
format = "[$symbol]($style) "
full_symbol = "🔋"
charging_symbol = "⚡️"
unknown_symbol = "💀"

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 50
style = "bold yellow"

[[battery.display]]
threshold = 100
style = "bold green"
