version: "3.5"
services:
    mysql_mysql:
        image: mysql:8
        container_name: mysql_mysql
        hostname: mysql_mysql
        restart: always
        ports:
            - 3306:3306
        networks:
            - mysql_net
        env_file:
            - ./common.env
        environment:
            - MYSQL_ROOT_PASSWORD=chinese
        volumes:
            - ./mysql:/docker-entrypoint-initdb.d
            - ./mysql/mysql.cnf:/etc/mysql/conf.d/my.cnf
            - ~/data/mysql/logs:/logs
            - ~/data/mysql/data:/var/lib/mysql 
networks:
    mysql_net:
        driver: bridge