version: "3.5"
services:
    nacos_mysql:
        image: mysql:8
        container_name: nacos_mysql
        hostname: nacos_mysql
        restart: always
        ports:
            - 3306:3306
        networks:
            - nacos_net
        env_file:
            - ./common.env
        environment:
            - MYSQL_ROOT_PASSWORD=chinese
        volumes:
            - ./mysql:/docker-entrypoint-initdb.d
            - ./mysql/mysql.cnf:/etc/mysql/conf.d/my.cnf
            - ~/data/mysql/logs:/logs
            - ~/data/mysql/data:/var/lib/mysqls
    nacos_nacos:
        image: nacos/nacos-server:1.3.1
        container_name: nacos_nacos
        hostname: nacos_nacos
        restart: always
        ports:
            - 8848:8848
            - 9555:9555
        networks:
            - nacos_net
        env_file:
            - ./common.env
            - ./nacos/nacos.env
        volumes:
            - ./nacos/custom.properties:/home/nacos/init.d/custom.properties
            - ~/data/nacos/logs:/home/nacos/logs
        depends_on:
            - nacos_mysql
networks:
    nacos_net:
        driver: bridge