version: "3.5"
services:
    nacos-mysql:
        image: mysql:8
        container_name: nacos-mysql
        hostname: nacos-mysql
        restart: always
        ports:
            - 3306:3306
        networks:
            - nacos-net
        env_file:
            - ./common.env
        environment:
            - MYSQL_ROOT_PASSWORD=chinese
        volumes:
            - ./mysql:/docker-entrypoint-initdb.d
    nacos-nacos:
        image: nacos/nacos-server:1.3.2
        container_name: nacos-nacos
        hostname: nacos-nacos
        restart: always
        ports:
            - 8848:8848
            - 9555:9555
        networks:
            - nacos-net
        env_file:
            - ./common.env
            - ./nacos/nacos.env
        volumes:
            - ./nacos/custom.properties:/home/nacos/init.d/custom.properties
            - ~/repository/docker/nacos/logs:/home/nacos/logs
        depends_on:
            - nacos-mysql
networks:
    nacos-net:
        driver: bridge