version: "3.5"
services:
    rocketmq_namesrv:
        image: apacherocketmq/rocketmq:4.5.0
        container_name: rocketmq_namesrv
        hostname: rocketmq_namesrv
        restart: always
        ports:
            - 9876:9876
        networks:
            - rocketmq_net
        env_file:
            - ./common.env
        volumes:
            - ~/data/rocketmq/namesrv/logs:/home/rocketmq/logs
        command: sh mqnamesrv
    rocketmq_broker:
        image: apacherocketmq/rocketmq:4.5.0
        container_name: rocketmq_broker
        hostname: rocketmq_broker
        restart: always
        ports:
            - 10909:10909
            - 10911:10911
            - 10912:10912
        networks:
            - rocketmq_net
        env_file:
            - ./common.env
            - ./rocketmq/rocketmq.env
        volumes:
            - ./rocketmq/broker-a.conf:/home/rocketmq/rocketmq-4.5.0/conf/broker.conf
            - ~/data/rocketmq/broker/logs:/home/rocketmq/logs
            - ~/data/rocketmq/broker/store:/home/rocketmq/store
        command: sh mqbroker -n rocketmq_namesrv:9876 -c ../conf/broker.conf
        depends_on:
            - rocketmq_namesrv
    rocketmq_console:
        image: apacherocketmq/rocketmq-console:2.0.0
        container_name: rocketmq_console
        hostname: rocketmq_console
        restart: always
        ports:
            - 8080:8080
        networks:
            - rocketmq_net
        env_file:
            - ./common.env
        environment:
            - JAVA_OPTS=-Drocketmq.namesrv.addr=rocketmq_namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false
        depends_on:
            - rocketmq_broker
networks:
    rocketmq_net:
        driver: bridge