version: "3.5"
services:
    rocketmq-namesrv:
        image: apacherocketmq/rocketmq:4.5.0
        container_name: rocketmq-namesrv
        hostname: rocketmq-namesrv
        restart: always
        ports:
            - 9876:9876
        networks:
            - rocketmq-net
        env_file:
            - ./common.env
        volumes:
            - ~/data/rocketmq/namesrv/logs:/home/rocketmq/logs
        command: sh mqnamesrv
    rocketmq-broker:
        image: apacherocketmq/rocketmq:4.5.0
        container_name: rocketmq-broker
        hostname: rocketmq-broker
        restart: always
        ports:
            - 10909:10909
            - 10911:10911
            - 10912:10912
        networks:
            - rocketmq-net
        env_file:
            - ./common.env
            - ./rocketmq/rocketmq.env
        volumes:
            - ./rocketmq/broker-a.conf:/home/rocketmq/rocketmq-4.5.0/conf/broker.conf
            - ~/data/rocketmq/broker/logs:/home/rocketmq/logs
            - ~/data/rocketmq/broker/store:/home/rocketmq/store
        command: sh mqbroker -n rocketmq-namesrv:9876 -c ../conf/broker.conf
        depends_on:
            - rocketmq-namesrv
    rocketmq-console:
        image: apacherocketmq/rocketmq-console:2.0.0
        container_name: rocketmq-console
        hostname: rocketmq-console
        restart: always
        ports:
            - 8080:8080
        networks:
            - rocketmq-net
        env_file:
            - ./common.env
        environment:
            - JAVA_OPTS=-Drocketmq.namesrv.addr=rocketmq-namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false
        depends_on:
            - rocketmq-broker
networks:
    rocketmq-net:
        driver: bridge