version: "3.5"
services:
    zk-zk1:
        image: zookeeper
        container_name: zk-zk1
        hostname: zk-zk1
        restart: always
        ports:
            - 2181:2181
            - 8081:8080 # admin /commands
        networks:
            - zk-net
        env_file:
            - ./common.env
            - ./zookeeper/zookeeper.env
        environment:
            - ZOO_MY_ID=1
            - ZOO_LOG4J_PROP=INFO, CONSOLE, DailyRollingAppender
            # - ZOO_LOG_FILE=zookeeper.log # zkServer.sh 已写死
        volumes:
            - ./zookeeper/zoo.cfg:/conf/zoo.cfg
            - ./zookeeper/log4j.properties:/conf/log4j.properties
            - ~/data/zk1/data:/data
            - ~/data/zk1/logs:/logs
    zk-zk2:
        image: zookeeper
        container_name: zk-zk2
        hostname: zk-zk2
        restart: always
        ports:
            - 2182:2181
            - 8082:8080
        networks:
            - zk-net
        env_file:
            - ./common.env
            - ./zookeeper/zookeeper.env
        environment:
            - ZOO_MY_ID=2
        volumes:
            - ./zookeeper/zoo.cfg:/conf/zoo.cfg
    zk-zk3:
        image: zookeeper
        container_name: zk-zk3
        hostname: zk-zk3
        restart: always
        ports:
            - 2183:2181
            - 8083:8080
        networks:
            - zk-net
        env_file:
            - ./common.env
            - ./zookeeper/zookeeper.env
        environment:
            - ZOO_MY_ID=3
        volumes:
            - ./zookeeper/zoo.cfg:/conf/zoo.cfg
    zk-zoonavigator:
        image: elkozmon/zoonavigator
        container_name: zk-zoonavigator
        hostname: zk-zoonavigator
        restart: always
        ports:
            - 9000:9000
        networks:
            - zk-net
        env_file:
            - ./common.env
        environment:
            - HTTP_PORT=9000
            - CONNECTION_ZK_NAME=zk-cluster
            - CONNECTION_ZK_CONN=zk-zk1:2181
        depends_on:
            - zk-zk1
            - zk-zk2
            - zk-zk3
networks:
    zk-net:
        driver: bridge