version: '3'
services:
  proxy-nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ~/doc:/doc:ro
  db-mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ~/data/mysql:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: chinese
      # MYSQL_USER: china
      # MYSQL_PASSWORD: chinese
      # MYSQL_DATABASE: school
  