apiVersion: v1
kind: Service
metadata:
  name: nginx-node-port-service
spec:
  type: NodePort
  selector:
    app: nginx-pod                # POD选择器(后台服务POD)
  ports:
  - name: http
    port: 80                      # 服务监听的端口号
    targetPort: 80                # 容器的端口号
    nodePort: 31000               # nodePort: 30000-32767
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-map
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      server {
        listen  80;
        location /fs/ {
          alias /;
          autoindex on;
        }
        location / {
          proxy_pass http://env-cluster-ip-service;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-pod              # POD选择器(监控的POD)
  replicas: 1                     # Deployment需要保持POD的数量
  template:
    metadata:
      labels:
        app: nginx-pod            # 自动生成POD标签
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.15
        ports:
        - containerPort: 80       # 容器监听的端口号
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx   # 挂载目录
      volumes:                    # 挂载磁盘配置
      - name: nginx-conf
        configMap:
          name: nginx-config-map
          items:                  # 需要挂载的内容KEY -- 挂载文件名配置
          - key: nginx.conf
            path: nginx.conf