version: '3'
services:
  db-redis:
    container_name: db-redis
    image: redis:alpine
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    ports:
      - 6379:6379