version: '3'
services:
  web-nginx:
    container_name: web-nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./mime.types:/etc/nginx/mime.types
      - ./proxy.conf:/etc/nginx/proxy.conf
      - /home/china/doc:/doc