eval "$(dbus-launch --sh-syntx --exit-with-session)"
export XMODIFIERS="@im=fcitx"
export QT_IM_MODULE=fcitx
export GTK_IM_MODULE=fcitx
fcitx &
guake &
exec ck-launch-session dbus-launch --exit-with-session startlxqt