[cargo-new]
email = "pickjob@126.com"
name = "吴胜"
vcs = "git"

[source.crates-io]
registry = "https://github.com/rust-lang/crates.io-index"
# 替换成任一镜像源
replace-with = 'tuna'
# replace-with = 'ustc'
# replace-with = 'rustcc'
# 清华大学
[source.tuna]
registry = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git"
# 中国科学技术大学
[source.ustc]
registry = "git://mirrors.ustc.edu.cn/crates.io-index"
# rustcc社区
[source.rustcc]
registry = "git://crates.rustcc.cn/crates.io-index"

[target.x86_64-pc-windows-gnu]
linker = "C:\\msys64\\mingw64\\bin\\gcc.exe"
ar = "C:\\msys64\\mingw64\\bin\\ar.exe"
